site_name: Phases Assessment Instrument
site_url: https://buffalo-ontology-group.github.io/phases-assessment-instrument/
repo_url: https://github.com/Buffalo-Ontology-Group/phases-assessment-instrument
site_description: A tool for assessing the phases of a project.

plugins:
  - search
  - mermaid2:
      version: 10.9.0
  - redirects: # reference: https://github.com/mkdocs/mkdocs-redirects
      redirect_maps:
        'home.md': 'index.md'  # redirects "/home" to "/"
        'ASTI_Schema.md': 'asti_schema.md'
        'schema.md': 'asti_schema.md'
markdown_extensions:
  - admonition
  - tables
  - pymdownx.magiclink
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

nav:
  - Home: /
  - ASTI Schema: asti_schema.md
  - STE Schema: ste_schema.md
