site_name: Phases Assessment Instrument
site_description: A tool for assessing the phases of a project.
theme:
  name: material
nav:
  - Home: index.md
  - ASTI Schema:
    - Overview: schema/asti_schema_overview.md
    - Classes: schema/asti_classes.md