# .github/workflows/deploy.yml

name: Deploy MkDocs Site to GitHub Pages (using gh-pages branch)

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main  # Or 'master' if that's your default branch
    paths:
      - 'mkdocs.yml' # Only trigger if the mkdocs.yml file changes
      - src/schema/**.yaml
      - 'src/docs/*.md'
      - 'src/docs/*.html'
      - 'docs/images/*'
      - Makefile
      - requirements.txt
      # Add other paths that trigger documentation rebuild if needed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# This is specifically for actions that push to branches.
permissions:
  contents: write # Required to push to the gh-pages branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip' # Cache pip dependencies

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- Build the MkDocs site ---
      # # This step will generate the static site files in the 'site/' directory by default
      - name: Build MkDocs site
        run: |
          make gendoc
      #   # Alternatively, if not using make: mkdocs build

      - name: Deploy MkDocs site to gh-pages
        run: |
          mkdir -p docs
          mkdir -p docs/images
          touch docs/.nojekyll
          make gendoc
          mkdocs gh-deploy --force